#!/usr/bin/env bash
# Launch prism + Firefox in one shot, wired up to diagnose HDR. Designed for
# TTY runs where the text console freezes once prism grabs DRM master, so you
# can't configure the client after the fact. A sibling of scripts/tty-test.sh,
# specialized for Firefox HDR debugging:
#
#   - prism runs with the color-management protocol layer at debug level, so
#     the wp_color_manager_v1.get_output stub and surface-feedback path show up.
#   - Firefox runs in a dedicated, pre-seeded profile with gfx.wayland.hdr on
#     and VA-API hardware decode forced (HDR video needs VP9-profile2 / AV1).
#   - Firefox's own MOZ_LOG (Dmabuf / WidgetWayland / PlatformDecoderModule) is
#     captured to a file so we can see *its* format-negotiation decision —
#     notably the "no HDR-capable YUV dmabuf format → fall back to SDR" path
#     (see Mozilla bug 1967366), which is the prime suspect given prism only
#     advertises RGB dmabuf fourccs (no P010/NV12).
#
# Usage:
#   scripts/firefox-test.sh [seconds]
#
# Env knobs:
#   URL          page Firefox opens. Default: a 4K-HDR YouTube demo. A local
#                  HDR clip is far more deterministic than YouTube (no manual
#                  quality/HDR selection, no autoplay gating), e.g.:
#                    URL='file:///home/christian/media/hdr-clip.mkv'
#   FIREFOX_BIN  override the firefox binary (default: `command -v firefox`).
#   PROFILE      Firefox profile dir (default: $XDG_CACHE_HOME/prism-firefox-test).
#                  Seeded with user.js each run. Point it at your real profile
#                  if you need logins/cookies — but then a desktop Firefox on
#                  that profile must not be running.
#   MOZ_LOG      override the Firefox log spec (default below). Append modules
#                  with e.g. MOZ_LOG="$DEFAULT,Compositor:5".
#   FORCE_HDR    if set, also write gfx.wayland.hdr.force-enabled=true (use when
#                  the display isn't auto-detected as HDR).
#   OUTPUT/DEPTH same meaning as tty-test.sh (prism `run` positional args).
#   NO_CLIENT    if set, don't launch Firefox (point an external one at the socket).
#   PRISM_CRUMBS / PRISM_WATCHDOG_SECS  same as tty-test.sh.
#
# After it exits, look at:
#   - ./firefox-prism.log    compositor stdout/stderr (prism_protocols=debug)
#   - ./firefox-client.log   Firefox stdout/stderr (GTK / EGL / VA-API init)
#   - ./firefox-moz.log*     Firefox MOZ_LOG (one file per process; *.child-PID)
#   - ${PRISM_CRUMBS}        fsync'd per-frame breadcrumbs

set -euo pipefail

SECS=${1:-60}

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

FIREFOX_BIN=${FIREFOX_BIN:-"$(command -v firefox || true)"}
PRISM_BIN="$ROOT/target/release/prism"
PRISM_LOG="$ROOT/firefox-prism.log"
CLIENT_LOG="$ROOT/firefox-client.log"
SCRIPT_LOG="$ROOT/firefox-test.log"
MOZ_LOG_BASE="$ROOT/firefox-moz.log"
PROFILE=${PROFILE:-"${XDG_CACHE_HOME:-$HOME/.cache}/prism-firefox-test"}
URL=${URL:-"https://www.youtube.com/watch?v=LXb3EKWsInQ"}  # Costa Rica 4K 60fps HDR

# Mirror everything we print to a log file so we can inspect what happened
# after prism's TTY grab freezes the console.
: > "$SCRIPT_LOG"
exec > >(tee -a "$SCRIPT_LOG") 2>&1
say() { echo "[firefox-test $(date +%H:%M:%S.%3N)] $*"; }
say "script start (pid=$$, args=[$*])"
trap 'rc=$?; say "ERR at line $LINENO (rc=$rc)"; exit $rc' ERR

if [[ -z "$FIREFOX_BIN" ]]; then
    say " no firefox binary found (set FIREFOX_BIN=...)"
    exit 1
fi

export PRISM_CRUMBS=${PRISM_CRUMBS:-"$ROOT/firefox.crumbs"}
export PRISM_WATCHDOG_SECS=${PRISM_WATCHDOG_SECS:-$((SECS + 5))}
export PRISM_MAX_RUNTIME_SECS=${PRISM_MAX_RUNTIME_SECS:-$SECS}
# prism_protocols at debug surfaces the color-management negotiation (the
# get_output stub logs at debug); keep the renderer at info to avoid per-frame
# flood. smithay=info still catches protocol errors / client disconnects.
export RUST_LOG=${RUST_LOG:-"prism=info,prism_protocols=debug,smithay=info"}
export RUST_BACKTRACE=${RUST_BACKTRACE:-full}

# Build everything we need.
say " building prism"
cargo build --release -p prism

# Compose `prism run` args (positional output + depth, like tty-test.sh).
PRISM_ARGS=(run)
if [[ -n "${OUTPUT:-}" ]]; then
    PRISM_ARGS+=("$OUTPUT" "${DEPTH:-10}")
elif [[ -n "${DEPTH:-}" ]]; then
    say " WARNING: DEPTH set without OUTPUT — ignored (prism CLI is positional)"
fi

# ── Seed the Firefox profile ────────────────────────────────────────────────
# Re-written every run so pref edits here take effect; cache/etc. is preserved
# between runs for speed.
mkdir -p "$PROFILE"
{
    echo '// Generated by scripts/firefox-test.sh — re-written each run.'
    echo '// --- HDR / color management ---'
    # NO_HDR=1 disables Firefox's Wayland HDR path (diagnostic: isolates the
    # HDR video-compositing path from the rest). Default on.
    if [[ -n "${NO_HDR:-}" ]]; then
        echo 'user_pref("gfx.wayland.hdr", false);'
    else
        echo 'user_pref("gfx.wayland.hdr", true);'
        if [[ -n "${FORCE_HDR:-}" ]]; then
            echo 'user_pref("gfx.wayland.hdr.force-enabled", true);'
        fi
    fi
    echo '// --- Hardware video decode (HDR video = VP9 profile2 / AV1 via VA-API) ---'
    echo 'user_pref("media.ffmpeg.vaapi.enabled", true);'
    echo 'user_pref("media.hardware-video-decoding.force-enabled", true);'
    echo 'user_pref("media.rdd-ffmpeg.enabled", true);'
    echo '// --- Wayland / dmabuf ---'
    echo 'user_pref("widget.dmabuf.force-enabled", true);'
    echo '// --- Make the test deterministic: allow autoplay, cut first-run noise ---'
    echo 'user_pref("media.autoplay.default", 0);'
    echo 'user_pref("media.autoplay.blocking_policy", 0);'
    echo 'user_pref("browser.aboutwelcome.enabled", false);'
    echo 'user_pref("browser.startup.homepage_override.mstone", "ignore");'
    echo 'user_pref("browser.shell.checkDefaultBrowser", false);'
    echo 'user_pref("datareporting.policy.dataSubmissionEnabled", false);'
    echo 'user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);'
} > "$PROFILE/user.js"
say " seeded profile $PROFILE/user.js (FORCE_HDR=${FORCE_HDR:+1})"

# ── Firefox environment ─────────────────────────────────────────────────────
# `sync` flushes each log line (so a crash doesn't lose the tail); `timestamp`
# prefixes wall-clock times. MOZ_LOG_FILE makes the parent + each child write
# its own file (base, then base.child-<pid>).
DEFAULT_MOZ_LOG="sync,timestamp,Dmabuf:5,WidgetWayland:5,PlatformDecoderModule:5"
export MOZ_LOG=${MOZ_LOG:-"$DEFAULT_MOZ_LOG"}
export MOZ_LOG_FILE="$MOZ_LOG_BASE"
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland
export MOZ_CRASHREPORTER_DISABLE=1   # no GUI crash reporter on a frozen TTY

RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
say " XDG_RUNTIME_DIR=$RUNTIME_DIR"
say " firefox: $FIREFOX_BIN"
say " URL: $URL"
say " MOZ_LOG: $MOZ_LOG"

# Launch prism. It grabs the TTY's DRM master so the console freezes —
# everything from here on is invisible until prism exits.
say " launching: prism ${PRISM_ARGS[*]} (seconds=$SECS, watchdog=${PRISM_WATCHDOG_SECS}s)"
: > "$PRISM_LOG"
: > "$CLIENT_LOG"
: > "$PRISM_CRUMBS"
rm -f "$MOZ_LOG_BASE"*   # clear stale per-process logs from a prior run

"$PRISM_BIN" "${PRISM_ARGS[@]}" >"$PRISM_LOG" 2>&1 &
PRISM_PID=$!
say " prism pid=$PRISM_PID"

cleanup() {
    # Kill Firefox + its child processes (GPU/content) by profile path, then prism.
    pkill -TERM -f "$PROFILE" 2>/dev/null || true
    if [[ -n "${CLIENT_PID:-}" ]] && kill -0 "$CLIENT_PID" 2>/dev/null; then
        kill -TERM "$CLIENT_PID" 2>/dev/null || true
    fi
    if kill -0 "$PRISM_PID" 2>/dev/null; then
        kill -TERM "$PRISM_PID" 2>/dev/null || true
        sleep 0.5
        kill -KILL "$PRISM_PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT INT TERM

# Wait for prism's wayland socket name to appear in its log.
SOCKET=""
for _ in $(seq 1 80); do  # up to ~8s
    sleep 0.1
    if ! kill -0 "$PRISM_PID" 2>/dev/null; then
        say " prism exited before socket appeared; see $PRISM_LOG"
        exit 1
    fi
    SOCKET=$(grep -oE 'WAYLAND_DISPLAY=[a-zA-Z0-9_.-]+' "$PRISM_LOG" 2>/dev/null \
        | head -n1 | cut -d= -f2 || true)
    [[ -n "$SOCKET" ]] && break
done

if [[ -z "$SOCKET" ]]; then
    say " no WAYLAND_DISPLAY line in $PRISM_LOG within 8s"
    exit 1
fi
say " prism socket: $SOCKET (file: $RUNTIME_DIR/$SOCKET)"
if [[ ! -S "$RUNTIME_DIR/$SOCKET" ]]; then
    say " WARNING: $RUNTIME_DIR/$SOCKET does not exist as a socket — Firefox may fail to connect"
fi

if [[ -n "${NO_CLIENT:-}" ]]; then
    say " NO_CLIENT set — skipping Firefox launch (prism socket: $SOCKET)"
    CLIENT_PID=""
else
    # --no-remote + --new-instance + a dedicated profile keep this off any
    # already-running desktop Firefox.
    say " launching Firefox (profile=$PROFILE)"
    WAYLAND_DISPLAY="$SOCKET" XDG_RUNTIME_DIR="$RUNTIME_DIR" \
        "$FIREFOX_BIN" --no-remote --new-instance -profile "$PROFILE" \
        --new-window "$URL" >"$CLIENT_LOG" 2>&1 &
    CLIENT_PID=$!
    say " firefox pid=$CLIENT_PID"
    sleep 0.5
    if kill -0 "$CLIENT_PID" 2>/dev/null; then
        say " firefox is alive after 500ms"
    else
        say " firefox exited immediately! head of client log:"
        head -n 20 "$CLIENT_LOG" 2>&1 | sed 's/^/   /'
    fi
fi

say " wait for prism pid=$PRISM_PID"
PRISM_RC=0
wait "$PRISM_PID" || PRISM_RC=$?
say " prism exited (rc=$PRISM_RC)"

# Make sure Firefox is gone too.
pkill -TERM -f "$PROFILE" 2>/dev/null || true
if [[ -n "${CLIENT_PID:-}" ]] && kill -0 "$CLIENT_PID" 2>/dev/null; then
    sleep 0.3
    kill -TERM "$CLIENT_PID" 2>/dev/null || true
fi
if [[ -n "${CLIENT_PID:-}" ]]; then
    wait "$CLIENT_PID" 2>/dev/null || true
fi

echo
say " summary"
echo "  compositor log: $PRISM_LOG"
echo "  firefox stderr: $CLIENT_LOG"
echo "  firefox MOZ_LOG: ${MOZ_LOG_BASE}*"
echo "  breadcrumbs:    $PRISM_CRUMBS"
echo
echo "── prism color-management / dmabuf lines ──"
grep -aiE 'color.?m|image.?desc|get_output|dmabuf advertised|dmabuf candidate|preferred description' \
    "$PRISM_LOG" 2>/dev/null | sed -E 's/\x1b\[[0-9;]*m//g' | tail -n 30 || true
echo
echo "── firefox HDR / dmabuf / fallback lines ──"
grep -aiE 'hdr|dmabuf|p010|nv12|color|bt2020|pq|fallback|fall back|sdr|vaapi|va-api' \
    "${MOZ_LOG_BASE}"* 2>/dev/null | tail -n 40 || echo "  (no MOZ_LOG output captured)"
